### ISSUE TITLE
Pls remove

### ISSUE THREAD

**Issue by gc00** [rachitpuri/Computer-Systems#1]
Hi @rachitpuri ,  Could you take down this solution to the mini-DMTCP homework?  I find that it is too much of a temptation to newer students to copy.  The university is now treating copying very seriously, and students can get hurt very badly from copying.  Thanks.  - Prof. Gene Cooperman

**Comment by rachitpuri** [comment]
Professor, I can understand the concern. I will remove it asap, consider it's done.
